engines:
  radon:
    enabled: true
  pep8:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python:
ratings:
  paths:
    - "**.py"
exclude_paths:
- "**/settings.py"
- "**/tests/"
- "README.md"
- "LICENCE"
- "*.yml"
- "**/conftest.py"
- "**/*.html"
- "static/*.css"
- "static/*.map"
- "static/govuk-0.18/"
- "static/icons/"
- "static/images/"
- "static/vendor/"
- "test_fixtures"
- "fixtures"
