# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 15:20
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='verification_code',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
