# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-30 11:38
from __future__ import unicode_literals

from django.db import migrations


def copy_date_joined_to_created(apps, schema_editor):
    User = apps.get_model("user", "User")
    for user in User.objects.all():
        user.created = user.date_joined
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20161130_1135'),
    ]

    operations = [
        migrations.RunPython(copy_date_joined_to_created),
    ]
