# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-30 10:30
from __future__ import unicode_literals

from django.db import migrations


def lowercase_email(apps, schema_editor):
    User = apps.get_model('user', 'User')
    for user in User.objects.all():
        user.email = user.email.lower()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_utm'),
    ]

    operations = [migrations.RunPython(
        lowercase_email,
        migrations.RunPython.noop
    )]
