# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 11:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_utm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='utm',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='Urchin Tracking Module query parameters passed in the URL'),
        ),
    ]
