# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hashed_uuid',
            field=models.CharField(default='', help_text="a hash representation of the object's UUID", max_length=200),
        ),
    ]
