# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-15 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_hashed_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hashed_uuid',
            field=models.CharField(default='', help_text="a hash representation of the object's id", max_length=200),
        ),
    ]
