# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-06 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190715_1043'),
        ('user', '0009_auto_20190702_1329'),
    ]

    operations = [
    ]
