# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-12 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190702_1329'),
        ('user', '0011_auto_20191107_1240'),
    ]

    operations = []
