# Generated by Django 2.2.7 on 2019-11-28 13:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_merge_20191112_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='utm',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, help_text='Urchin Tracking Module query parameters passed in the URL'
            ),
        ),
    ]
