# Generated by Django 2.2.13 on 2020-08-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_lessoncompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoncompleted',
            name='topic',
        ),
    ]
