# Generated by Django 2.2.15 on 2021-03-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_lessoncompleted_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='segment',
            field=models.CharField(
                blank=True,
                choices=[
                    ('SUSTAIN', 'Sustain'),
                    ('REASSURE', 'Reassure'),
                    ('PROMOTE', 'Promote'),
                    ('CHALLENGE', 'Challenge'),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
