# Generated by Django 2.2.15 on 2021-03-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_userprofile_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inactivity_notification',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
