# Generated by Django 2.2.15 on 2021-03-23 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_userprofile_segment'),
        ('user', '0017_user_inactivity_notification'),
    ]

    operations = []
