# Generated by Django 2.2.19 on 2021-03-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_merge_20210323_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inactivity_notification',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
