# Generated by Django 2.2.15 on 2021-03-24 18:14

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20210324_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('sso_user', models.IntegerField(blank=True, null=True)),
                ('company_user', models.IntegerField(blank=True, null=True)),
                ('company', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DataRetentionStatatics',
                'verbose_name_plural': 'DataRetentionStatatics',
            },
        ),
    ]
