# Generated by Django 2.2.19 on 2021-04-08 10:13

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_dataretentionstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('name', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                (
                    'question_type',
                    models.CharField(
                        choices=[
                            ('RADIO', 'radio'),
                            ('SELECTION', 'Selection'),
                            ('MULTIPLE_SELECTOR', 'Multiple selection'),
                            ('TEXT', 'text'),
                            ('COMPANY_LOOKUP', 'Company lookup'),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    'question_choices',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, help_text='Array of choices'
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Service')),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
        migrations.AlterModelOptions(
            name='dataretentionstatistics',
            options={'verbose_name': 'Data Retention Statistics', 'verbose_name_plural': 'Data Retention Statistics'},
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
