# Generated by Django 2.2.19 on 2021-04-12 16:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_add_sort_order_to_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='predefined_choices',
            field=models.CharField(
                blank=True,
                choices=[('EXPERTISE_REGION_CHOICES', 'EXPERTISE_REGION_CHOICES')],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_choices',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, help_text='Question parameters'
            ),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(
                choices=[
                    ('RADIO', 'radio'),
                    ('SELECTION', 'Selection'),
                    ('MULTIPLE_SELECTOR', 'Multiple selection'),
                    ('TEXT', 'text'),
                    ('COMPANY_LOOKUP', 'Company lookup'),
                ],
                max_length=20,
            ),
        ),
    ]
