# Generated by Django 2.2.27 on 2022-05-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20210429_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inactivity_notification_sent',
            field=models.DateTimeField(null=True, verbose_name='Notification sent'),
        ),
    ]
